name = "FellaCraft"
author = "Ganoodles"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fc8380af6251db5e6c177ea9b36e6191a6efd968de800ea4acd9576df82edd2"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
